---
- name: User Playbook
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks: 

  - name: add users
    user: 
      name: "{{item}}"
      state: present
    with_items:
    - bob
    - lisa
    - sam
    
 
 